import { z } from 'zod';

const text = z.string().max(30000);
const short = z.string().trim().min(1).max(300);
const identifier = z.string().uuid();
const maybeId = identifier.optional();
const list = z.array(z.string().max(1000)).max(100);
export const platforms = ['youtube', 'instagram', 'tiktok', 'facebook', 'linkedin', 'x', 'custom'];
export const workspaceSchema = z.object({ id: maybeId, name: short, objective: text.default(''), audience: text.default(''), voice: text.default(''), pillars: list.default([]), platforms: z.array(z.enum(platforms)).min(1).default(['youtube']), language: short.default('English'), timezone: short.default('Asia/Karachi'), constraints: text.default('') }).strict();
const variantSchema = z.object({ id: short, platform: z.enum(platforms), format: short, hook: text.default(''), script: text.default(''), caption: text.default(''), cta: text.default(''), title: text.default(''), duration: z.number().min(0).max(86400).nullable().default(null), master_revision: z.number().int().min(1), disclosures: text.default('') }).strict();
export const contentSchema = z.object({ id: maybeId, title: short, objective: text.default(''), audience: text.default(''), promise: text.default(''), pillar: text.default(''), campaign: text.default(''), series: text.default(''), script: text.default(''), cta: text.default(''), format: short.default('short_video'), platforms: z.array(z.enum(platforms)).min(1).default(['youtube']), planned_date: z.string().regex(/^$|^\d{4}-\d{2}-\d{2}$/).default(''), notes: text.default(''), variants: z.array(variantSchema).max(30).default([]) }).strict();
const sourceSchema = z.object({ id: maybeId, content_id: identifier, claim: short, url: z.string().url().refine(v => /^https?:\/\//.test(v), 'Use an HTTP or HTTPS source URL.'), excerpt: text.default(''), verified_at: z.string().datetime().nullable().default(null), status: z.enum(['unverified', 'supported', 'disputed']).default('unverified') }).strict();
const assetSchema = z.object({ id: maybeId, content_id: identifier, name: short, type: z.enum(['image', 'video', 'audio', 'document', 'other']), location: text.default(''), creator: text.default(''), license: text.default(''), rights_status: z.enum(['unknown', 'reviewed', 'restricted']).default('unknown'), rights_evidence: text.default(''), synthetic: z.boolean().default(false), notes: text.default('') }).strict();
const bibleSchema = z.object({ id: short, type: z.enum(['character', 'world', 'style', 'voice']), name: short, specification: text }).strict();
const shotSchema = z.object({ id: short, scene: short, start: z.number().min(0), duration: z.number().positive().max(3600), description: text, narration: text.default(''), prompt: text.default(''), references: list.default([]), acceptance: text.default('') }).strict();
const productionSchema = z.object({ id: maybeId, content_id: identifier, target_duration: z.number().positive().max(86400), bibles: z.array(bibleSchema).max(100).default([]), shots: z.array(shotSchema).max(500).default([]), notes: text.default('') }).strict();
const experimentSchema = z.object({ id: maybeId, title: short, hypothesis: text, platform: z.enum(platforms), variable: text.default(''), baseline: text.default(''), primary_metric: short, guardrails: text.default(''), end_condition: text.default(''), status: z.enum(['planned', 'running', 'completed', 'inconclusive']).default('planned'), result: text.default(''), evidence: text.default(''), limitations: text.default('') }).strict();
const knowledgeSchema = z.object({ id: maybeId, title: short, type: z.enum(['fact', 'decision', 'assumption', 'hypothesis', 'result', 'learning']), body: text, scope: text.default(''), evidence: text.default(''), experiment_id: identifier.nullable().default(null), status: z.enum(['proposed', 'reviewed', 'deprecated']).default('proposed') }).strict();
export const schemas = { source: sourceSchema, asset: assetSchema, production: productionSchema, experiment: experimentSchema, knowledge: knowledgeSchema };
export const scope = { workspace_id: identifier };
export const expected = z.number().int().positive().optional();
export const workflowSteps = ['brief', 'research', 'script', 'adaptation', 'review', 'export'];
